/*
Grafana SLO API

This API CRUDs SLO objects for the Grafana plugin.  Modifying an SLO object will create or update recording and alerting rules in a connected Prometheus instance and create or update dashboards in Grafana.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slo

import (
	"bytes"
	"encoding/json"
)

// checks if the SloV00RatioQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SloV00RatioQuery{}

// SloV00RatioQuery struct for SloV00RatioQuery
type SloV00RatioQuery struct {
	GroupByLabels []string        `json:"groupByLabels,omitempty"`
	SuccessMetric SloV00MetricDef `json:"successMetric"`
	TotalMetric   SloV00MetricDef `json:"totalMetric"`
}

type _SloV00RatioQuery SloV00RatioQuery

// NewSloV00RatioQuery instantiates a new SloV00RatioQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSloV00RatioQuery(successMetric SloV00MetricDef, totalMetric SloV00MetricDef) *SloV00RatioQuery {
	this := SloV00RatioQuery{}
	this.SuccessMetric = successMetric
	this.TotalMetric = totalMetric
	return &this
}

// NewSloV00RatioQueryWithDefaults instantiates a new SloV00RatioQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSloV00RatioQueryWithDefaults() *SloV00RatioQuery {
	this := SloV00RatioQuery{}
	return &this
}

// GetGroupByLabels returns the GroupByLabels field value if set, zero value otherwise.
func (o *SloV00RatioQuery) GetGroupByLabels() []string {
	if o == nil || IsNil(o.GroupByLabels) {
		var ret []string
		return ret
	}
	return o.GroupByLabels
}

// GetGroupByLabelsOk returns a tuple with the GroupByLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SloV00RatioQuery) GetGroupByLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupByLabels) {
		return nil, false
	}
	return o.GroupByLabels, true
}

// HasGroupByLabels returns a boolean if a field has been set.
func (o *SloV00RatioQuery) HasGroupByLabels() bool {
	if o != nil && !IsNil(o.GroupByLabels) {
		return true
	}

	return false
}

// SetGroupByLabels gets a reference to the given []string and assigns it to the GroupByLabels field.
func (o *SloV00RatioQuery) SetGroupByLabels(v []string) {
	o.GroupByLabels = v
}

// GetSuccessMetric returns the SuccessMetric field value
func (o *SloV00RatioQuery) GetSuccessMetric() SloV00MetricDef {
	if o == nil {
		var ret SloV00MetricDef
		return ret
	}

	return o.SuccessMetric
}

// GetSuccessMetricOk returns a tuple with the SuccessMetric field value
// and a boolean to check if the value has been set.
func (o *SloV00RatioQuery) GetSuccessMetricOk() (*SloV00MetricDef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessMetric, true
}

// SetSuccessMetric sets field value
func (o *SloV00RatioQuery) SetSuccessMetric(v SloV00MetricDef) {
	o.SuccessMetric = v
}

// GetTotalMetric returns the TotalMetric field value
func (o *SloV00RatioQuery) GetTotalMetric() SloV00MetricDef {
	if o == nil {
		var ret SloV00MetricDef
		return ret
	}

	return o.TotalMetric
}

// GetTotalMetricOk returns a tuple with the TotalMetric field value
// and a boolean to check if the value has been set.
func (o *SloV00RatioQuery) GetTotalMetricOk() (*SloV00MetricDef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalMetric, true
}

// SetTotalMetric sets field value
func (o *SloV00RatioQuery) SetTotalMetric(v SloV00MetricDef) {
	o.TotalMetric = v
}

func (o SloV00RatioQuery) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SloV00RatioQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupByLabels) {
		toSerialize["groupByLabels"] = o.GroupByLabels
	}
	toSerialize["successMetric"] = o.SuccessMetric
	toSerialize["totalMetric"] = o.TotalMetric
	return toSerialize, nil
}

func (o *SloV00RatioQuery) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varSloV00RatioQuery := _SloV00RatioQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSloV00RatioQuery)

	if err != nil {
		return err
	}

	*o = SloV00RatioQuery(varSloV00RatioQuery)

	return err
}

type NullableSloV00RatioQuery struct {
	value *SloV00RatioQuery
	isSet bool
}

func (v NullableSloV00RatioQuery) Get() *SloV00RatioQuery {
	return v.value
}

func (v *NullableSloV00RatioQuery) Set(val *SloV00RatioQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableSloV00RatioQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableSloV00RatioQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSloV00RatioQuery(val *SloV00RatioQuery) *NullableSloV00RatioQuery {
	return &NullableSloV00RatioQuery{value: val, isSet: true}
}

func (v NullableSloV00RatioQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSloV00RatioQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
