/*
Grafana SLO API

This API CRUDs SLO objects for the Grafana plugin.  Modifying an SLO object will create or update recording and alerting rules in a connected Prometheus instance and create or update dashboards in Grafana.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slo

import (
	"bytes"
	"encoding/json"
)

// checks if the ApiReportCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiReportCreateResponse{}

// ApiReportCreateResponse struct for ApiReportCreateResponse
type ApiReportCreateResponse struct {
	Message string `json:"message"`
	Uuid    string `json:"uuid"`
}

type _ApiReportCreateResponse ApiReportCreateResponse

// NewApiReportCreateResponse instantiates a new ApiReportCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiReportCreateResponse(message string, uuid string) *ApiReportCreateResponse {
	this := ApiReportCreateResponse{}
	this.Message = message
	this.Uuid = uuid
	return &this
}

// NewApiReportCreateResponseWithDefaults instantiates a new ApiReportCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiReportCreateResponseWithDefaults() *ApiReportCreateResponse {
	this := ApiReportCreateResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *ApiReportCreateResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ApiReportCreateResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ApiReportCreateResponse) SetMessage(v string) {
	o.Message = v
}

// GetUuid returns the Uuid field value
func (o *ApiReportCreateResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *ApiReportCreateResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *ApiReportCreateResponse) SetUuid(v string) {
	o.Uuid = v
}

func (o ApiReportCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiReportCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *ApiReportCreateResponse) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varApiReportCreateResponse := _ApiReportCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varApiReportCreateResponse)

	if err != nil {
		return err
	}

	*o = ApiReportCreateResponse(varApiReportCreateResponse)

	return err
}

type NullableApiReportCreateResponse struct {
	value *ApiReportCreateResponse
	isSet bool
}

func (v NullableApiReportCreateResponse) Get() *ApiReportCreateResponse {
	return v.value
}

func (v *NullableApiReportCreateResponse) Set(val *ApiReportCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiReportCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiReportCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiReportCreateResponse(val *ApiReportCreateResponse) *NullableApiReportCreateResponse {
	return &NullableApiReportCreateResponse{value: val, isSet: true}
}

func (v NullableApiReportCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiReportCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
