/*
Grafana SLO API

This API CRUDs SLO objects for the Grafana plugin.  Modifying an SLO object will create or update recording and alerting rules in a connected Prometheus instance and create or update dashboards in Grafana.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slo

import (
	"bytes"
	"encoding/json"
)

// checks if the SloV00MaintenanceEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SloV00MaintenanceEvent{}

// SloV00MaintenanceEvent struct for SloV00MaintenanceEvent
type SloV00MaintenanceEvent struct {
	EndTimeIso8601   *string `json:"endTimeIso8601,omitempty"`
	Name             string  `json:"name"`
	StartTimeIso8601 string  `json:"startTimeIso8601"`
}

type _SloV00MaintenanceEvent SloV00MaintenanceEvent

// NewSloV00MaintenanceEvent instantiates a new SloV00MaintenanceEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSloV00MaintenanceEvent(name string, startTimeIso8601 string) *SloV00MaintenanceEvent {
	this := SloV00MaintenanceEvent{}
	this.Name = name
	this.StartTimeIso8601 = startTimeIso8601
	return &this
}

// NewSloV00MaintenanceEventWithDefaults instantiates a new SloV00MaintenanceEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSloV00MaintenanceEventWithDefaults() *SloV00MaintenanceEvent {
	this := SloV00MaintenanceEvent{}
	return &this
}

// GetEndTimeIso8601 returns the EndTimeIso8601 field value if set, zero value otherwise.
func (o *SloV00MaintenanceEvent) GetEndTimeIso8601() string {
	if o == nil || IsNil(o.EndTimeIso8601) {
		var ret string
		return ret
	}
	return *o.EndTimeIso8601
}

// GetEndTimeIso8601Ok returns a tuple with the EndTimeIso8601 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SloV00MaintenanceEvent) GetEndTimeIso8601Ok() (*string, bool) {
	if o == nil || IsNil(o.EndTimeIso8601) {
		return nil, false
	}
	return o.EndTimeIso8601, true
}

// HasEndTimeIso8601 returns a boolean if a field has been set.
func (o *SloV00MaintenanceEvent) HasEndTimeIso8601() bool {
	if o != nil && !IsNil(o.EndTimeIso8601) {
		return true
	}

	return false
}

// SetEndTimeIso8601 gets a reference to the given string and assigns it to the EndTimeIso8601 field.
func (o *SloV00MaintenanceEvent) SetEndTimeIso8601(v string) {
	o.EndTimeIso8601 = &v
}

// GetName returns the Name field value
func (o *SloV00MaintenanceEvent) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SloV00MaintenanceEvent) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SloV00MaintenanceEvent) SetName(v string) {
	o.Name = v
}

// GetStartTimeIso8601 returns the StartTimeIso8601 field value
func (o *SloV00MaintenanceEvent) GetStartTimeIso8601() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartTimeIso8601
}

// GetStartTimeIso8601Ok returns a tuple with the StartTimeIso8601 field value
// and a boolean to check if the value has been set.
func (o *SloV00MaintenanceEvent) GetStartTimeIso8601Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTimeIso8601, true
}

// SetStartTimeIso8601 sets field value
func (o *SloV00MaintenanceEvent) SetStartTimeIso8601(v string) {
	o.StartTimeIso8601 = v
}

func (o SloV00MaintenanceEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SloV00MaintenanceEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndTimeIso8601) {
		toSerialize["endTimeIso8601"] = o.EndTimeIso8601
	}
	toSerialize["name"] = o.Name
	toSerialize["startTimeIso8601"] = o.StartTimeIso8601
	return toSerialize, nil
}

func (o *SloV00MaintenanceEvent) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varSloV00MaintenanceEvent := _SloV00MaintenanceEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSloV00MaintenanceEvent)

	if err != nil {
		return err
	}

	*o = SloV00MaintenanceEvent(varSloV00MaintenanceEvent)

	return err
}

type NullableSloV00MaintenanceEvent struct {
	value *SloV00MaintenanceEvent
	isSet bool
}

func (v NullableSloV00MaintenanceEvent) Get() *SloV00MaintenanceEvent {
	return v.value
}

func (v *NullableSloV00MaintenanceEvent) Set(val *SloV00MaintenanceEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableSloV00MaintenanceEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableSloV00MaintenanceEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSloV00MaintenanceEvent(val *SloV00MaintenanceEvent) *NullableSloV00MaintenanceEvent {
	return &NullableSloV00MaintenanceEvent{value: val, isSet: true}
}

func (v NullableSloV00MaintenanceEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSloV00MaintenanceEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
