/*
Grafana SLO API

This API CRUDs SLO objects for the Grafana plugin.  Modifying an SLO object will create or update recording and alerting rules in a connected Prometheus instance and create or update dashboards in Grafana.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slo

import (
	"bytes"
	"encoding/json"
)

// checks if the SloV00AlertEnrichment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SloV00AlertEnrichment{}

// SloV00AlertEnrichment struct for SloV00AlertEnrichment
type SloV00AlertEnrichment struct {
	Type string `json:"type"`
}

type _SloV00AlertEnrichment SloV00AlertEnrichment

// NewSloV00AlertEnrichment instantiates a new SloV00AlertEnrichment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSloV00AlertEnrichment(type_ string) *SloV00AlertEnrichment {
	this := SloV00AlertEnrichment{}
	this.Type = type_
	return &this
}

// NewSloV00AlertEnrichmentWithDefaults instantiates a new SloV00AlertEnrichment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSloV00AlertEnrichmentWithDefaults() *SloV00AlertEnrichment {
	this := SloV00AlertEnrichment{}
	return &this
}

// GetType returns the Type field value
func (o *SloV00AlertEnrichment) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SloV00AlertEnrichment) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SloV00AlertEnrichment) SetType(v string) {
	o.Type = v
}

func (o SloV00AlertEnrichment) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SloV00AlertEnrichment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *SloV00AlertEnrichment) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varSloV00AlertEnrichment := _SloV00AlertEnrichment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varSloV00AlertEnrichment)

	if err != nil {
		return err
	}

	*o = SloV00AlertEnrichment(varSloV00AlertEnrichment)

	return err
}

type NullableSloV00AlertEnrichment struct {
	value *SloV00AlertEnrichment
	isSet bool
}

func (v NullableSloV00AlertEnrichment) Get() *SloV00AlertEnrichment {
	return v.value
}

func (v *NullableSloV00AlertEnrichment) Set(val *SloV00AlertEnrichment) {
	v.value = val
	v.isSet = true
}

func (v NullableSloV00AlertEnrichment) IsSet() bool {
	return v.isSet
}

func (v *NullableSloV00AlertEnrichment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSloV00AlertEnrichment(val *SloV00AlertEnrichment) *NullableSloV00AlertEnrichment {
	return &NullableSloV00AlertEnrichment{value: val, isSet: true}
}

func (v NullableSloV00AlertEnrichment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSloV00AlertEnrichment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
