/*
Grafana SLO API

This API CRUDs SLO objects for the Grafana plugin.  Modifying an SLO object will create or update recording and alerting rules in a connected Prometheus instance and create or update dashboards in Grafana.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ThresholdQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThresholdQuery{}

// ThresholdQuery struct for ThresholdQuery
type ThresholdQuery struct {
	GroupByLabels []string `json:"groupByLabels,omitempty"`
	Metric MetricDef `json:"metric"`
	Threshold Threshold `json:"threshold"`
}

type _ThresholdQuery ThresholdQuery

// NewThresholdQuery instantiates a new ThresholdQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThresholdQuery(metric MetricDef, threshold Threshold) *ThresholdQuery {
	this := ThresholdQuery{}
	this.Metric = metric
	this.Threshold = threshold
	return &this
}

// NewThresholdQueryWithDefaults instantiates a new ThresholdQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThresholdQueryWithDefaults() *ThresholdQuery {
	this := ThresholdQuery{}
	return &this
}

// GetGroupByLabels returns the GroupByLabels field value if set, zero value otherwise.
func (o *ThresholdQuery) GetGroupByLabels() []string {
	if o == nil || IsNil(o.GroupByLabels) {
		var ret []string
		return ret
	}
	return o.GroupByLabels
}

// GetGroupByLabelsOk returns a tuple with the GroupByLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThresholdQuery) GetGroupByLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupByLabels) {
		return nil, false
	}
	return o.GroupByLabels, true
}

// HasGroupByLabels returns a boolean if a field has been set.
func (o *ThresholdQuery) HasGroupByLabels() bool {
	if o != nil && !IsNil(o.GroupByLabels) {
		return true
	}

	return false
}

// SetGroupByLabels gets a reference to the given []string and assigns it to the GroupByLabels field.
func (o *ThresholdQuery) SetGroupByLabels(v []string) {
	o.GroupByLabels = v
}

// GetMetric returns the Metric field value
func (o *ThresholdQuery) GetMetric() MetricDef {
	if o == nil {
		var ret MetricDef
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *ThresholdQuery) GetMetricOk() (*MetricDef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *ThresholdQuery) SetMetric(v MetricDef) {
	o.Metric = v
}

// GetThreshold returns the Threshold field value
func (o *ThresholdQuery) GetThreshold() Threshold {
	if o == nil {
		var ret Threshold
		return ret
	}

	return o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value
// and a boolean to check if the value has been set.
func (o *ThresholdQuery) GetThresholdOk() (*Threshold, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threshold, true
}

// SetThreshold sets field value
func (o *ThresholdQuery) SetThreshold(v Threshold) {
	o.Threshold = v
}

func (o ThresholdQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThresholdQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupByLabels) {
		toSerialize["groupByLabels"] = o.GroupByLabels
	}
	toSerialize["metric"] = o.Metric
	toSerialize["threshold"] = o.Threshold
	return toSerialize, nil
}

func (o *ThresholdQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metric",
		"threshold",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varThresholdQuery := _ThresholdQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varThresholdQuery)

	if err != nil {
		return err
	}

	*o = ThresholdQuery(varThresholdQuery)

	return err
}

type NullableThresholdQuery struct {
	value *ThresholdQuery
	isSet bool
}

func (v NullableThresholdQuery) Get() *ThresholdQuery {
	return v.value
}

func (v *NullableThresholdQuery) Set(val *ThresholdQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableThresholdQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableThresholdQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThresholdQuery(val *ThresholdQuery) *NullableThresholdQuery {
	return &NullableThresholdQuery{value: val, isSet: true}
}

func (v NullableThresholdQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThresholdQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


