/*
Grafana SLO API

This API CRUDs SLO objects for the Grafana plugin.  Modifying an SLO object will create or update recording and alerting rules in a connected Prometheus instance and create or update dashboards in Grafana.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HistogramQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HistogramQuery{}

// HistogramQuery struct for HistogramQuery
type HistogramQuery struct {
	GroupByLabels []string `json:"groupByLabels,omitempty"`
	Metric MetricDef `json:"metric"`
	Percentile float64 `json:"percentile"`
	Threshold Threshold `json:"threshold"`
}

type _HistogramQuery HistogramQuery

// NewHistogramQuery instantiates a new HistogramQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHistogramQuery(metric MetricDef, percentile float64, threshold Threshold) *HistogramQuery {
	this := HistogramQuery{}
	this.Metric = metric
	this.Percentile = percentile
	this.Threshold = threshold
	return &this
}

// NewHistogramQueryWithDefaults instantiates a new HistogramQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHistogramQueryWithDefaults() *HistogramQuery {
	this := HistogramQuery{}
	return &this
}

// GetGroupByLabels returns the GroupByLabels field value if set, zero value otherwise.
func (o *HistogramQuery) GetGroupByLabels() []string {
	if o == nil || IsNil(o.GroupByLabels) {
		var ret []string
		return ret
	}
	return o.GroupByLabels
}

// GetGroupByLabelsOk returns a tuple with the GroupByLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HistogramQuery) GetGroupByLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupByLabels) {
		return nil, false
	}
	return o.GroupByLabels, true
}

// HasGroupByLabels returns a boolean if a field has been set.
func (o *HistogramQuery) HasGroupByLabels() bool {
	if o != nil && !IsNil(o.GroupByLabels) {
		return true
	}

	return false
}

// SetGroupByLabels gets a reference to the given []string and assigns it to the GroupByLabels field.
func (o *HistogramQuery) SetGroupByLabels(v []string) {
	o.GroupByLabels = v
}

// GetMetric returns the Metric field value
func (o *HistogramQuery) GetMetric() MetricDef {
	if o == nil {
		var ret MetricDef
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *HistogramQuery) GetMetricOk() (*MetricDef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *HistogramQuery) SetMetric(v MetricDef) {
	o.Metric = v
}

// GetPercentile returns the Percentile field value
func (o *HistogramQuery) GetPercentile() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Percentile
}

// GetPercentileOk returns a tuple with the Percentile field value
// and a boolean to check if the value has been set.
func (o *HistogramQuery) GetPercentileOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percentile, true
}

// SetPercentile sets field value
func (o *HistogramQuery) SetPercentile(v float64) {
	o.Percentile = v
}

// GetThreshold returns the Threshold field value
func (o *HistogramQuery) GetThreshold() Threshold {
	if o == nil {
		var ret Threshold
		return ret
	}

	return o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value
// and a boolean to check if the value has been set.
func (o *HistogramQuery) GetThresholdOk() (*Threshold, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threshold, true
}

// SetThreshold sets field value
func (o *HistogramQuery) SetThreshold(v Threshold) {
	o.Threshold = v
}

func (o HistogramQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HistogramQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupByLabels) {
		toSerialize["groupByLabels"] = o.GroupByLabels
	}
	toSerialize["metric"] = o.Metric
	toSerialize["percentile"] = o.Percentile
	toSerialize["threshold"] = o.Threshold
	return toSerialize, nil
}

func (o *HistogramQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metric",
		"percentile",
		"threshold",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHistogramQuery := _HistogramQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHistogramQuery)

	if err != nil {
		return err
	}

	*o = HistogramQuery(varHistogramQuery)

	return err
}

type NullableHistogramQuery struct {
	value *HistogramQuery
	isSet bool
}

func (v NullableHistogramQuery) Get() *HistogramQuery {
	return v.value
}

func (v *NullableHistogramQuery) Set(val *HistogramQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableHistogramQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableHistogramQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHistogramQuery(val *HistogramQuery) *NullableHistogramQuery {
	return &NullableHistogramQuery{value: val, isSet: true}
}

func (v NullableHistogramQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHistogramQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


