/*
Grafana SLO API

This API CRUDs SLO objects for the Grafana plugin.  Modifying an SLO object will create or update recording and alerting rules in a connected Prometheus instance and create or update dashboards in Grafana.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slo

import (
	"bytes"
	"encoding/json"
)

// checks if the ApiSLOCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSLOCreateResponse{}

// ApiSLOCreateResponse struct for ApiSLOCreateResponse
type ApiSLOCreateResponse struct {
	Message string `json:"message"`
	Uuid    string `json:"uuid"`
}

type _ApiSLOCreateResponse ApiSLOCreateResponse

// NewApiSLOCreateResponse instantiates a new ApiSLOCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSLOCreateResponse(message string, uuid string) *ApiSLOCreateResponse {
	this := ApiSLOCreateResponse{}
	this.Message = message
	this.Uuid = uuid
	return &this
}

// NewApiSLOCreateResponseWithDefaults instantiates a new ApiSLOCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSLOCreateResponseWithDefaults() *ApiSLOCreateResponse {
	this := ApiSLOCreateResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *ApiSLOCreateResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ApiSLOCreateResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ApiSLOCreateResponse) SetMessage(v string) {
	o.Message = v
}

// GetUuid returns the Uuid field value
func (o *ApiSLOCreateResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *ApiSLOCreateResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *ApiSLOCreateResponse) SetUuid(v string) {
	o.Uuid = v
}

func (o ApiSLOCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSLOCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *ApiSLOCreateResponse) UnmarshalJSON(data []byte) (err error) {
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	varApiSLOCreateResponse := _ApiSLOCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varApiSLOCreateResponse)

	if err != nil {
		return err
	}

	*o = ApiSLOCreateResponse(varApiSLOCreateResponse)

	return err
}

type NullableApiSLOCreateResponse struct {
	value *ApiSLOCreateResponse
	isSet bool
}

func (v NullableApiSLOCreateResponse) Get() *ApiSLOCreateResponse {
	return v.value
}

func (v *NullableApiSLOCreateResponse) Set(val *ApiSLOCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSLOCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSLOCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSLOCreateResponse(val *ApiSLOCreateResponse) *NullableApiSLOCreateResponse {
	return &NullableApiSLOCreateResponse{value: val, isSet: true}
}

func (v NullableApiSLOCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSLOCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
