/*
Grafana SLO API

This API CRUDs SLO objects for the Grafana plugin.  Modifying an SLO object will create or update recording and alerting rules in a connected Prometheus instance and create or update dashboards in Grafana.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SLOListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SLOListResponse{}

// SLOListResponse struct for SLOListResponse
type SLOListResponse struct {
	Slos []Slo `json:"slos"`
}

type _SLOListResponse SLOListResponse

// NewSLOListResponse instantiates a new SLOListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSLOListResponse(slos []Slo) *SLOListResponse {
	this := SLOListResponse{}
	this.Slos = slos
	return &this
}

// NewSLOListResponseWithDefaults instantiates a new SLOListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSLOListResponseWithDefaults() *SLOListResponse {
	this := SLOListResponse{}
	return &this
}

// GetSlos returns the Slos field value
func (o *SLOListResponse) GetSlos() []Slo {
	if o == nil {
		var ret []Slo
		return ret
	}

	return o.Slos
}

// GetSlosOk returns a tuple with the Slos field value
// and a boolean to check if the value has been set.
func (o *SLOListResponse) GetSlosOk() ([]Slo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Slos, true
}

// SetSlos sets field value
func (o *SLOListResponse) SetSlos(v []Slo) {
	o.Slos = v
}

func (o SLOListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SLOListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["slos"] = o.Slos
	return toSerialize, nil
}

func (o *SLOListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"slos",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSLOListResponse := _SLOListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSLOListResponse)

	if err != nil {
		return err
	}

	*o = SLOListResponse(varSLOListResponse)

	return err
}

type NullableSLOListResponse struct {
	value *SLOListResponse
	isSet bool
}

func (v NullableSLOListResponse) Get() *SLOListResponse {
	return v.value
}

func (v *NullableSLOListResponse) Set(val *SLOListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSLOListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSLOListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSLOListResponse(val *SLOListResponse) *NullableSLOListResponse {
	return &NullableSLOListResponse{value: val, isSet: true}
}

func (v NullableSLOListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSLOListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


