name: Generate Clients

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    env:
      REPO_NAME: slo-openapi-client
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.26.1'
      - name: Generate Client
        uses: grafana/shared-workflows/actions/generate-openapi-clients@8ef55db5803bf7fc92e32ca4a4f488657f3f53fe # v1.1.0
        with:
          package-name: slo
          spec-path: openapi.yaml
          commit-changes: "false"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          commit-message: "Update generated OpenAPI clients"
          title: "Update OpenAPI clients"
          body: "Auto-generated client update after OpenAPI spec change."
          branch: auto/update-openapi-clients