name: Generate Clients

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make generate-clients
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update clients and publish
